POST localhost:8080/api/file/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="small-size-image.jpg"

< ../test_image/small-size-image.jpg
--WebAppBoundary--